# Generated by Django 5.0.6 on 2024-07-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('Technologies', models.CharField(max_length=250)),
                ('features', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('source_code', models.URLField(blank=True, null=True)),
                ('thumbnail_img', models.ImageField(null=True, upload_to='project_imgs/')),
                ('imgs', models.ImageField(null=True, upload_to='project_imgs/')),
            ],
        ),
    ]
