# Generated by Django 5.0.6 on 2024-07-08 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='imgs',
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_imgs/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio_app_1.project')),
            ],
        ),
    ]
