# Generated by Django 5.0.6 on 2024-07-08 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app_1', '0002_remove_project_imgs_projectimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=350)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='portfolio_app_1.project')),
            ],
        ),
    ]
