# Generated by Django 5.0.6 on 2024-07-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app_1', '0003_projectfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
    ]
