# Generated by Django 5.0.6 on 2024-07-10 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app_1', '0009_project_status_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
