# Generated by Django 5.0.6 on 2024-07-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app_1', '0012_alter_projectfeature_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfeature',
            name='header',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
