# Generated by Django 5.0.6 on 2024-07-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_description_blogpost_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_img',
            field=models.ImageField(null=True, upload_to='blog_imgs'),
        ),
    ]
